name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 1 * * *'  # runs daily at 01:15 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git Identity - 23f2002978@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "23f2002978@ds.study.iitm.ac.in"

      - name: Make a daily commit
        run: |
          echo "Daily log: $(date -u)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "🤖 Daily update: $(date -u)" || echo "Nothing to commit"
          git push
